### ISSUE TITLE
[Bug][v9]  this.actor.getEmbeddedEntity is not a function

### ISSUE THREAD

**Issue by SamuelWeeks** [jopeek/fvtt-loot-sheet-npc-5e#222]
**Describe the bug**
Getting A type Error When clicking on the buy button of Merchant

LootsheetNPC5e.js:443 Uncaught TypeError: this.actor.getEmbeddedEntity is not a function
[Detected 1 package: lootsheetnpc5e]
    at LootSheetNPC5e._buyItem (LootsheetNPC5e.js:443)
    at HTMLAnchorElement.<anonymous> (LootsheetNPC5e.js:197)
    at HTMLAnchorElement.dispatch (jquery.min.js:2)
    at HTMLAnchorElement.v.handle (jquery.min.js:2)

**To Reproduce**
Click the buy button

**Expected behavior**
Buy Item

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Brave/Chrome

**Additional context**
Hope this helps

**Comment by jopeek** [comment]
Not yet compatible with v9 but thanks for the report and we’ll get to it soon :)

**Comment by DanielBoettner** [comment]
Call has to be 

```js
this.actor.getEmbeddedDocument()
```

I tested it to be working with v0.8.9 as well and will push the changes to develop later today.

**Comment by DanielBoettner** [comment]
Will be fixed in next release.

**Comment by DanielBoettner** [comment]
@SamuelWeeks could you test if [v3.4.1](https://github.com/jopeek/fvtt-loot-sheet-npc-5e/releases/tag/v3.4.1) solves this issue?

Can't guarantee anything but it might.

**Comment by DanielBoettner** [comment]
for manual install this is my latest dev build.
This seem to work in v8 and v9
[3425.zip](https://github.com/jopeek/fvtt-loot-sheet-npc-5e/files/7775798/3425.zip)
